version: '3.5'
# 网络配置
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

# 服务容器配置
services:
  smsserver:                                # 自定义容器名称
    build:
      context: ./server # 指定构建使用的 Dockerfile 文件
    environment:                         # 设置环境变量
      - TZ=${TZ}
    privileged: true
    ports:                               # 设置端口映射
      - "8888:8888"
    networks:
      - backend
    restart: always                      # 指定容器退出后的重启策略为始终重启


  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/www/root/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    networks:
      - backend

