// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"smsserver/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sms/:phone",
				Handler: postSmsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sms/:phone",
				Handler: getSmsHandler(serverCtx),
			},
		},
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(3000*time.Millisecond),
	)
}
