// Code generated by goctl. DO NOT EDIT.
package types

type GetSmsReq struct {
	Phone string `path:"phone"`
	Count int    `form:"count,optional,default=1"`
}

type GetSmsResp struct {
	Contents []string `json:"contents"`
}

type PutSmsReq struct {
	Phone   string `path:"phone"`
	Content string `json:"content"`
}

type PutSmsResp struct {
}
